### ISSUE TITLE
Setters and Getters for startDate and endDate

### ISSUE THREAD

**Issue by ermalmeco** [eaxdev/Java-JsonResume-Validator#5]
Hello, I am new to java programming but I was doing a project using this library and I see that there is no setter or getter for period abstract class. I have the fields in the database but when I retrieve them to send to the front I don't have how to map in work class or education class. etc.. 
Why is it like that? Can you help me, please?

**Comment by eaxdev** [comment]
Yes, it was a bug. I released a new version 0.0.2. A few hours later she will have to appear in a Maven Central repository
